{% set name = "types-xmltodict" %}
{% set version = "1.0.1.20260408" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 64a079b1c0fc09197246c905d54cccb7c86fd49c834b5f6265e84dfaf200f5b7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for xmltodict
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - corneliusroemer
