{% set name = "types-xmltodict" %}
{% set version = "1.0.1.20250920" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3a2a97b7c3247251d715452e7bd86b9f0567fb91e407164344c93390d9bbbe88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for xmltodict
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - corneliusroemer
