{% set name = "types-xmltodict" %}
{% set version = "0.14.0.20241009" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-xmltodict-{{ version }}.tar.gz
  sha256: 9224c2422c5b6359cf826685b4ee50b14dc2cb9134561ab793ef6b03dd7108e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for xmltodict
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - corneliusroemer
